//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Part()
        {
            this.ProductPartMaps = new HashSet<ProductPartMap>();
            this.ProductPartMaps1 = new HashSet<ProductPartMap>();
        }
    
        public int partID { get; set; }
        public int pid { get; set; }
        public string desc { get; set; }
        public string image { get; set; }
        public Nullable<int> price { get; set; }
        public string cate { get; set; }
        public Nullable<int> noparts { get; set; }
        public string name { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPartMap> ProductPartMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPartMap> ProductPartMaps1 { get; set; }
    }
}
